<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-UMGIKAS2" failures="1" tests="7" name="SwagLabs Tests" time="29.932" errors="0" timestamp="2025-09-09T17:47:10 IST">
  <testcase classname="testcases.InvalidLoginTest" name="loginWithInvalidCredentials" time="6.095"/>
  <testcase classname="testcases.ValidLoginTest" name="loginWithMultipleUsers" time="9.904">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.ValidLoginTest.loginWithMultipleUsers(ValidLoginTest.java:31)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- loginWithMultipleUsers -->
  <testcase classname="testcases.ValidLoginTest" name="loginWithMultipleUsers" time="8.74"/>
  <testcase classname="testcases.ValidLoginTest" name="loginWithMultipleUsers" time="8.535"/>
  <testcase classname="testcases.E2EFlowTest" name="loginAddToCartCheckout" time="11.051"/>
  <testcase classname="testcases.InvalidLoginTest" name="loginWithInvalidCredentials" time="3.921"/>
  <testcase classname="testcases.InvalidLoginTest" name="loginWithInvalidCredentials" time="0.601"/>
</testsuite> <!-- SwagLabs Tests -->
