<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-UMGIKAS2" failures="3" tests="4" name="UI Tests" time="37.755" errors="0" timestamp="2025-07-12T11:53:49 IST">
  <testcase classname="tests.NegativeLoginTest" name="loginWithInvalidCredentials" time="0.676">
    <failure type="java.lang.AssertionError" message="Error message mismatch expected [Epic sadface: Username and password do not match] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: Error message mismatch expected [Epic sadface: Username and password do not match] but found [Epic sadface: Username and password do not match any user in this service]
at tests.NegativeLoginTest.loginWithInvalidCredentials(NegativeLoginTest.java:25)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidCredentials -->
  <testcase classname="tests.NegativeLoginTest" name="loginWithInvalidCredentials" time="1.96"/>
  <testcase classname="tests.NegativeLoginTest" name="loginWithInvalidCredentials" time="1.859">
    <failure type="java.lang.AssertionError" message="Error message mismatch expected [Epic sadface: Username and password do not match] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: Error message mismatch expected [Epic sadface: Username and password do not match] but found [Epic sadface: Username and password do not match any user in this service]
at tests.NegativeLoginTest.loginWithInvalidCredentials(NegativeLoginTest.java:25)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidCredentials -->
  <testcase classname="tests.NegativeLoginTest" name="loginWithInvalidCredentials" time="0.07">
    <failure type="java.lang.IllegalArgumentException" message="Keys to send should be a not null CharSequence">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:98)
at pages.LoginPage.login(LoginPage.java:19)
at tests.NegativeLoginTest.loginWithInvalidCredentials(NegativeLoginTest.java:20)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidCredentials -->
</testsuite> <!-- UI Tests -->
